name = "Firefly"
uuid = "f0119071-79de-41eb-b75f-69c202aeece9"
authors = ["Griffin Heier <griffinheier@gmail.com>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
HDF5 = "0.17.2"
PyCall = "1.96.4"
